steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/gcpsa-sandbox/edward-demo-run-cr/${_IMAGE_NAME}', '.']
    env:
      - 'IMAGE_NAME=${_IMAGE_NAME}'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/gcpsa-sandbox/edward-demo-run-cr/${_IMAGE_NAME}']
    env:
      - 'IMAGE_NAME=${_IMAGE_NAME}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'edward-demo-cr-service', '--image', 'asia-east1-docker.pkg.dev/gcpsa-sandbox/edward-demo-run-cr/${_IMAGE_NAME}', '--platform', 'managed', '--region', 'asia-east1', '--allow-unauthenticated']
    env:
      - 'IMAGE_NAME=${_IMAGE_NAME}'

images:
  - 'asia-east1-docker.pkg.dev/gcpsa-sandbox/edward-demo-run-cr/${_IMAGE_NAME}'

substitutions:
  _IMAGE_NAME: 'edward-demo-cr-web'
